PlasmaPy/plasmapy.github.io

README.md, pull_from_github.py, web/conf.py, web/pages/index.html, web/pages/license.md
Changes:
- Cleaned up config.py from any mentions to me, generalized to PlasmaPy developers.
- Added License to webpage footer, autogenerated from https://github.com/PlasmaPy/plasmapy.github.io/blob/master/LICENSE.md using `pull_from_github.py`
- Added instructions on how to build the website to `README.md` (Note that the first time the web is built there's no need to go to the `src` branch, as it will be created automatically by `nikola github_deploy`).
- Changed tags and demo information from` index.html`.
=> Clean up confs

.travis.yml, CNAME
Travis CI is able to create the 'CNAME' file when deploying on GitHub
Pages automatically.
GitHub-Issue: #8
GitHub-Issue: #5
=> Let Travis CI set 'CNAME' when deploying on Pages

.gitignore, web/conf.py, web/pages/index.md, web/posts/plasmapy-v01-release.rst
The purpose of this pull request is to make a landing page for the website, akin to [Astropy's landing page](https://www.astropy.org/).  Thus far I moved the blog posts to `news/`, changed the order of the tabs, and created `web/pages/index.md` for the new landing page.  We still need to discuss what would go in there.  
Closes #30.  Closes #28.
=> Create landing page, reorganize website, and add funding acknowledgment

web/files/assets/css/custom.css, web/pages/meetings/1st_workshop_2020_at_bryn_mawr/index.md
Update the 1st PlasmaPy Workshop meeting page to indicate the meeting has been cancelled and that we intend to replace the workshop with a webinar series.
=> Update 1st PlasmaPy Workshop page with Cancellation Note

web/pages/contribute.md, web/pages/vision.md, web/posts/plasmapy-v01-release.rst, web/posts/plasmapy-v011-bugfix-release.rst, web/posts/plasmapy-v020-release.rst
This PR repairs a hand full of links that are either broken or miss-directed (e.g. going to the `master` version of RTDs vs the `latest` version).
Links in the PlasmaPy v0.1.0 post are now directed to the `v0.1` branch of RTDs.
=> Fix broken/miss-directed documentation links

web/pages/meetings/index.md, web/pages/meetings/weekly.md
Add a page for PlasmaPy's weekly meetings with all the appropriate info...
* jitsi link
* time
* calendar
* minutes and agenda
* matrix chat
* brief summary
=> Add a weekly meetings page

web/conf.py, web/files/assets/css/custom.css, web/pages/index.md
This PR adds links to our new YouTube Channel and 1st YouTube video.
1. A link to our YouTube channel is placed in the "About" top-menu.
1. Custom CSS styles created to place a YouTube video on the landing page, centered and at 80% width.
1. Our inaugural YouTube video is embedded on our landing page.
1. I tweaked the feature card widths to be 33.33% page width, vs 33%.  The difference was visually noticeable with the YouTube video below it.
=> Add Initial YouTube Content

web/files/assets/css/custom.css, web/pages/index.md
This PR does...
1. Improves CSS style for `.feature-card` (looks the same as before but with less needed code).
1. Add  CSS style `.feature-card-banner` for banner like cards.  This is used for the survey link.
1. Add a link to the 2020 PlasmaPy Survey on our landing page.
This is what the banner looks like...
This is what it looks like when you hover over the banner before clicking...
=> Add 2020 PlasmaPy Survey to our landing page

web/files/assets/css/custom.css
Update CSS so the height of the `.feature-card-banner` class will auto adjust to content.  This is needed for good visibility on  mobile platforms.  Before the text would overflow the `div` element.
=> Follow up to PR #65 - update CSS for vertical sizing

web/pages/index.md
The link to the PlasmaPy examples page was broken. This PR updates the link to point to the correct page in the documentation.
=> Fix examples link

web/pages/index.md, web/pages/meetings/office_hours.md
In #72, we announced special weekly office hours on 2020 Oct 7 & 8.  This PR changes that page and the feature card to announce a weekly time for office hours (tentatively Thursdays at 2 pm EDT).
**This should be merged no earlier than 2020 Oct 8.**
=> Announce time for weekly "office" hours

web/pages/meetings/aps/62nd_dpp_mini_conf_followups.md, web/pages/meetings/index.md
1. Create a page for the follow-up meetings associated with the 62nd APS DPP Mini-Conference on open-source software.
1. Add the page to the main meetings page.
1. On the main meetings page, update the "Office" Hours time and move it to the weekly meetings section.
=> Create Page for 62nd DPP Mini-Conf Follow-up Meetings

web/pages/index.md, web/pages/license.md, web/pages/meetings/aps/62nd_dpp_mini_conf_followups.md, web/pages/meetings/index.md, web/pages/meetings/office_hours.md, web/pages/meetings/weekly.md
This PR changes the meeting times from 18 UTC to 19 UTC for the weekly meeting and office hours due to the change from daylight savings time to standard time in the US.  The times remain at 2 pm ET.  I consistentified the formatting of times, and stopped using 24-hour time for ET and PT since it's less common (and because I often end up having off-by-two errors...).  
I'm still hoping that there's a Nikola plugin hiding somewhere out there that would be able to convert a time we provide to the reader's local time zone.  One can dream...
=> Update times to reflect time change (plus updating copyright date & funding info)

conf.py
I saw https://github.com/sunpy/sunpy.org/pull/265/files and thought, hey, pretty. Let's do that as well.
This will let us point people to `plasmapy.org/chat` instead of whatever the complicated element links. We can also always change the redirect on the website.
=> Add `plasmapy.org/chat` redirect

data/affiliated_pkgs.json, files/assets/css/custom.css, shortcodes/build_affiliated_pkg_list.tmpl
This adds [PyMethes](https://gitlab.com/ethz_hvl/pymethes) to the affiliated pkgs page.
In addition, I've made some improvements to the build_affiliated_pkg_list.tmpl shortcode and CSS to improve display of single line long descriptions and to ignore case when sorting the pkg list.
The PyMethes render looks like....
=> Add PyMethes to affiliated pkgs

pages/meetings/office_hours.md, pages/meetings/weekly.md
This PR adds dates when we will not hold our weekly meeting or office hours.  Apart from holidays, the dates & reasons are:
- June 23: simultaneous SULI tutorial
- July 12 & 14: hack week
- July 26: @namurphy at CSSI meeting (should we hold weekly meeting anyway?)
- October 18 & 20: APS DPP meeting
=> Put dates without weekly meetings or office hours on website

pages/meetings/office_hours.md, pages/meetings/weekly.md
This PR expands the dates where office hours and the community meeting will not be held around the end of the year.
=> Update seasonal community meeting & office hour cancellation dates

pages/index.md
This PR removes the survey card that was at the top of the webpage, at least for now, since the date on it was from 2021.  I'd be happy for us to update it and add it back in, though.
=> Remove survey link from 2021

.github/workflows/deploy.yml
Our GitHub Action for deploying broke because we were using old versions of things, so this updates them.
=> Update versions of GitHub Actions

.github/workflows/deploy.yml
I just started getting this error:
```
REPO: PlasmaPy/plasmapy.github.io
ACTOR: namurphy
==> Preparing...
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
```
This PR adds that command.
=> Add safe directory for deployment GitHub Action

pages/meetings/office_hours.md, pages/meetings/weekly.md
Because there are going to be a bunch of days this summer where we won't be having our weekly meeting or office hours, I figured I'd add them to the event pages.
=> Add away dates for summer 2023 for meetings & office hours

pages/meetings/office_hours.md, pages/meetings/weekly.md
Most of the people who have been hosting meetings and office hours will be taking an extended holiday or returning from Antarctica in the next ∼2 months, so I'm going to cancel meetings & office hours.
Since the current NSF CSSI award that supports PlasmaPy development will be ending in early to mid 2025, we may put office hours on hiatus for a while.
=> Cancel weekly meetings an office hours in December 2024 & January 2025

pages/meetings/office_hours.md, pages/meetings/weekly.md
This PR removes some temporary text from the website which stated dates that we didn't hold office hours or our weekly meeting.
=> Update office hour and meeting cancellations

pages/meetings/summer-school-2024.md
The PlasmaPy Summer School was held in the summer of 2024, so the logistics sections of the summer school pages are no longer needed.  This PR removes those sections and puts the page in the past tense.
> [!NOTE]
> If we are lucky enough to hold a summer school at Bryn Mawr in the future, we can look back into version control for the older versions of this page. Yay for version control!
=> Adapt summer school page to use past tense

pages/meetings/index.md, pages/meetings/weekly.md
Since the NSF CSSI award is ending imminently, we are changing the meeting times from weekly to fortnightly.  The next meeting will be on October 6.
=> Change meeting times to every other Monday at 1 pm ET
