PlasmaPy/plasmapy.github.io

pull_from_github.py
requirements.txt
web/conf.py
web/files/assets/css/custom.css
web/pages/index.html
web/pages/vision.md

Fixing #6 
To-do list:
- - [x] Link to vision statement
- - [x] Matrix, Gitter, email list, biweekly telecons (with occasional tutorials)
- - [x] Raise issues on GitHub (can help guide the development roadmap!)
- - [x] Contribute code
- - [x] Ways to contribute besides contributing code
- - [x] Documentation Page
- - [x] Tutorials repository
- - [x] Link to conference posters on Zenodo

Add material to front page

---

.gitignore
web/conf.py
web/pages/about.html
web/pages/acknowledging.md
web/pages/contribute.md

Various small fixes

---

web/conf.py

And a couple minor changes I'd been meaning to do for a while.

Update conf.py for recent Nikola versions

---

web/conf.py
web/pages/meetings/2020_mini_conf_at_bryn_mawr/index.md

Alternative to #37, using the native localsearch plugin rather than Google.
Implements a fix as described in https://github.com/PlasmaPy/plasmapy.github.io/pull/37#issuecomment-594093129_ .

Localsearch-based search bar

---

web/posts/plasmapy-v01-release.rst
web/posts/plasmapy-v031-release.rst

Here is a draft blog post to announce our 0.3.1 release.  Suggestions are welcome!   I also updated a link in an earlier blog post.

Add post on version 0.3.1 release

---

web/posts/plasmapy-v031-release.rst

Fixes comments left by @rocco8773 in #43.
I just tried `nikola github_deploy` so the site should be rebuilding right now.

Make corrections to 0.3.1 blog post

---

.circleci/config.yml
pyproject.toml

Add PR builder

---

web/conf.py
web/files/assets/css/custom.css
web/pages/index.md

This PR should be merged after PR #65 
1. Adds Facebook link to the "Community" sub-menu and moves the YouTube link from the "About" sub-menu to the "Community" sub-menu.
1. Add social media links to the page footer and rename the GitHub link as GitHub.

Update social media links

---

web/pages/meetings/office_hours.md

Putting sentences that were on two lines into a single paragraph...

Minor formatting fix in first office hours page

---

web/pages/index.md

I added a Note to indicate users can try installing plasmapy using pip3 if pip is not working right away.

Update index.md to add note about pip3

---

pages/index.md

Replaces the survey link on the landing page to the 2021 survey.

Update Survey link to 2021 Survey

---

posts/plasmapy-v060-release.md

Here's a basic draft :) I'm going to crosspost it to my personal blog later, if you don't mind.

Add v0.6 announcement post

---

data/affiliated_pkgs.json

This adds [ALOHA](https://github.com/IRFM/ALOHA) to the affiliated pkgs page.
@jhillairet  Let me know how this looks to you and I'll merge it once I get your ok.  I have double check the home and repo links work.
The `ALOHA` render looks like....

Add ALOHA to affiliated pkgs

---

pages/index.md

Fix time of office hours on landing page

---

conf.py

~~I should still grep for the previous link, shouldn't I?~~ No more occurences of the previous link!

Correct the zoom link redirect

---

pages/meetings/index.md

The time for office hours is wrong on one of the pages, so this PR fixes it.
@rocco8773 — I think it's time maybe to get my own YOLO GitHub badge.  🥇

Fix office hours time

---

.pre-commit-config.yaml
conf.py
files/assets/css/custom.css
pyproject.toml

...keeping the configuration in `pyproject.toml`.

Add pre-commit configuration with codespell

---

.github/workflows/deploy.yml

This one is from the get-nikola docs.

Update GitHub Action for deployment

---

.github/workflows/deploy.yml

So, it turns out that the version of the GitHub Action in the Nikola example is quite out-of-date.  This PR updates it to the current version.

Update version of Nikola action

---

conf.py

#153 
Website functioned as expected after building locally!

Fix Issue 153: Remove references to Twitter account

---

pages/meetings/office_hours.md

- I'm shortening the office hour to 45 minutes since I have a conflict at that time every other week. It's also rare for anyone to show up at that point either.  
- I'm updating some of the cancellation dates for office hours.

Update office hours

---

conf.py
noxfile.py
pages/index.md
requirements.txt

This PR adds Nox sessions for:
- Building site
- Performing checks on the output
- Cleaning files

Add Nox sessions

---

.github/workflows/ci.yml

This PR adds GitHub workflows for building the website and performing Nikola checks. Follows up on #167.

Update continuous integration checks

---

pages/meetings/summer-school-2024.md

This PR follows up on #159 with some additions to the summer school page.  Things to do (either in this PR or later):

Update summer school page

---

pages/meetings/weekly.md

Since I'm likely to be family medical leave for the next few weeks, this PR is canceling the fortnightly meeting on Oct 6. I don't know yet if I'll be able to make it on Oct 20 or Nov 2.

Update meeting times
